version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore:"
    labels:
      - dependabot
    # Update Cargo.lock even when Cargo.toml constraints already allow the new version
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - dependabot
