version: 2
updates:
  - package-ecosystem: rust-toolchain
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependabot
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore:"
    labels:
      - dependabot
  - package-ecosystem: npm
    directory: "/vscode"
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore:"
    labels:
      - dependabot
    ignore:
      # vscode doesn't use latest node
      - dependency-name: "@types/node"
      # should match the version of `engines.vscode`
      - dependency-name: "@types/vscode"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependabot
