version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    target-branch: "main"
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore:"
    labels:
      - dependabot
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "main"
    schedule:
      interval: monthly
    labels:
      - dependabot
